name: win-arm64-build

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
        arch: [arm64]
        kind: [static, shared]

    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-Windows-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.kind }}
        cancel-in-progress: true    
    
    steps:
    - uses: actions/checkout@v4

    - name: Cache packages
      id: cache-xmake-windows
      uses: actions/cache@v4
      env:
        cache-name: cache-win-modules
      with:
        path: ~/.xmake
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
            
    - uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: 3.0.0
        actions-cache-folder: '.xmake-cache'
        actions-cache-key: 'windows_arm64'

    - name: configure
      shell: cmd
      run: |
        xmake f -c -a ${{ matrix.arch }} -k ${{ matrix.kind }} -y -vD --mysql=n --http_client_zip=y --http_client_ssl=n

    - name: build
      shell: cmd
      run: |
        xmake -b unit-test

    - name: test
      run: |
        xmake r unit-test        

